### PR TITLE
filter ignored issues

### LINKED ISSUE #15: Filter ignored issues
Currently, the request to get issues does not filter ignored issues:
```
postData := issuesPostData{
		Filters: issueFilters{
			Severities: []string{
				"high", "medium", "low",
			},
		},
	}
```
See the [API documentation](https://snyk.docs.apiary.io/#reference/projects/project-issues/list-all-issues) for more details. I'm working on a fix PR.

### PR DESCRIPTION
**Pull request by omerlh**
close #15

### CODE REVIEW

**Comment by Crevil** [comment]
What do you think of including them still, but instead adding a `ignored` prometheus label to it?

This way we can track both open and ignored vulnerabilities if we like by filtering on that?

```
snyk_vulnerabilities_total{organization="my-org",project="my-app",severity="high",issue_title="Privilege Escalation",ignored="true"} 1.0
```

**Comment by omerlh** [comment]
It's a bit more complex then what I added - requires also to update the dedupe function. Sounds like a big change to me...

**Comment by Crevil** [comment]
True. It's a bit more complicated. Does my provided solution still cover your needs?
If that's the case, I would prefer it and can provide the implementation in the coming days as well.

**Comment by omerlh** [comment]
Yes, it is. I'll close the PR for now...

**Comment by Crevil** [comment]
Got ya. I'll make sure to let you know when it's available. And thank you very much for your contributions.

**Comment by omerlh** [comment]
You welcome :) Looking forward to it!

**Comment by omerlh** [comment]
Hey, any estimation to when this might be available? We need this to improve our alerting...

**Comment by Crevil** [comment]
Sorry @omerlh . I got away from this again. Please see #17 and make sure it fits your needs.

**Comment by omerlh** [comment]
Yep, it will. The only downside - it will increase the number of metrics exposed by the exporter, but this is something we'll have to figure out. Looking forward to it!

**Comment by Crevil** [comment]
Yes, it will increase. If this turns out to be a problem, we might implement it in a more configurable way, so you can just filter them all out, as in your implementation.

Let me know if this becomes an issue we should look into.

**Comment by omerlh** [comment]
Will do! Thanks :)

**Pull request closed without merging**
